name: Create Azure resources

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: create resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          template: ${{ github.workspace }}/config/main.bicep
          parameters: 'namePrefix=${{ vars.AZURE_PREFIX }}'
          failOnStdErr: false